CREATE TABLE IF NOT EXISTS guns (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  caliber VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  availability BOOLEAN NOT NULL
);
